export const METHODOLOGY_NAMESPACE = 'methodology'

export const METHODOLOGY_DOCUMENTS = [
  {
    id: 'methodology-phase1-etude',
    topic: 'Phase 1 -- Étude du CTS et architecture',
    text: [
      "Phase 1 -- Étude du CTS et conception de l'architecture.",
      'Étude du Change and Transport System (CTS) de SAP : Workbench Request, Customizing',
      'Request, Transport Route, Import Queue, Transport Layer. Vérification du landscape réel',
      "de l'entreprise via STMS : le domaine DOMAIN_VE0 ne comporte que deux systèmes (VE0 en",
      'développement, QAS en qualité), sans système de production dans ce domaine -- une',
      "incohérence de route de transport a aussi été relevée. Architecture cible retenue en",
      'cinq couches : source de données SAP (E070/E071), couche d\'extraction ABAP, couche de',
      'stockage analytique (ZTR_TRANSPORT, ZTR_OBJECTS, ZTR_KPI), couche d\'exposition, couche',
      'de présentation (dashboard Power BI). Un catalogue de KPI (volume, stabilité, délai,',
      'risque, développeur) a été défini dès cette phase.',
    ].join(' '),
  },
  {
    id: 'methodology-phase2-extraction',
    topic: "Phase 2 -- Moteur d'extraction",
    text: [
      "Phase 2 -- Moteur d'extraction de données (programme Z_TRANSPORT_ANALYZER).",
      "L'audit du code réel a révélé trois anomalies : une limite artificielle à 100 lignes",
      'sans lien avec le volume réel, des dates d\'import QA/PRD et un statut simulés par une',
      'formule arbitraire (sy-tabix MOD 3/5) plutôt que lus depuis un historique réel, et la',
      'table ZTR_OBJECTS jamais alimentée malgré les objets lus en mémoire. Corrections',
      "apportées : limite portée à 500 lignes avec tri par date (ORDER BY as4date DESCENDING)",
      'pour éviter un plantage mémoire (TSV_TNEW_PAGE_ALLOC_FAILED) tout en gardant les',
      'transports les plus récents ; lecture des statuts réels depuis la table SAP TPSTAT ; et',
      "ajout d'une boucle d'insertion réelle dans ZTR_OBJECTS, qui a révélé un second défaut :",
      "la clé primaire de ZTR_OBJECTS n'avait que TR_NUMBER, empêchant plusieurs objets par",
      'transport -- corrigée en clé composite (TR_NUMBER + OBJ_NAME) via SE11 et SE14.',
    ].join(' '),
  },
  {
    id: 'methodology-phase3-risque',
    topic: 'Phase 3 -- Classification des risques',
    text: [
      'Phase 3 -- Moteur de classification des risques (programme Z_PHASE3_RISK_ENGINE).',
      "Grille de risque par type d'objet : TABL/DDLS/AUTH/SOBJ = 50 points (risque élevé),",
      'PROG/FUGR = 20 points (risque moyen), autres types = 5 points (risque faible), avec',
      "+20 points si le transport contient plus de 20 objets. L'audit a révélé un",
      'désalignement entre les 100 transports sélectionnés par ce moteur (sans tri) et les 500',
      'transports réellement extraits en Phase 2 -- corrigé en alignant la sélection (500',
      "lignes, même tri). Limites documentées mais non corrigées : la règle du cahier des",
      "charges qui ajoute 15 points pour un transport d'urgence n'est pas implémentable car",
      "ZTR_TRANSPORT n'a pas de champ EMERGENCY ; et certains gros packages SAP standard",
      'contiennent des objets',
      'techniquement dupliqués dans E071, provoquant des échecs d\'insertion partiels côté',
      'détail (le score global du transport reste néanmoins exact).',
    ].join(' '),
  },
  {
    id: 'methodology-phase4-kpi',
    topic: 'Phase 4 -- Moteur KPI',
    text: [
      "Phase 4 -- Moteur d'agrégation des indicateurs clés (programme Z_PHASE4_KPI_ENGINE).",
      'Trois sections calculées correctement dès l\'audit initial : KPI global, KPI par',
      'développeur (GROUP BY owner), KPI par niveau de risque. Anomalie détectée : la',
      'section censée alimenter ZTR_KPI avec un historique mensuel calculait en réalité les',
      "mêmes compteurs globaux sans filtre de date, étiquetés par le mois d'exécution du",
      "programme -- rendant impossible toute analyse de tendance réelle. Corrigé en regroupant",
      'les transports par leur mois de création réel (CREATION_DATE), avec un jeu de KPI',
      'distinct par mois. Validation : 10 mois distincts détectés, avec des volumes réellement',
      'différents (de 1 à 191 transports selon le mois).',
    ].join(' '),
  },
  {
    id: 'methodology-phase5-dashboard',
    topic: 'Phase 5 -- Tableau de bord',
    text: [
      'Phase 5 -- Tableau de bord (programme Z_PHASE5_DASHBOARD, Power BI, site web).',
      'Deux restitutions complémentaires : un tableau de bord natif SAP (grille ALV) et un',
      'tableau de bord Power BI. Anomalie détectée sur la grille ALV : seul le libellé "long"',
      'des colonnes était renseigné, affichant des noms techniques illisibles (ex. "Char20")',
      'au lieu de libellés compréhensibles -- corrigé en renseignant les libellés court, moyen',
      'et long pour les neuf colonnes. Le tableau de bord Power BI comporte quatre pages',
      '(Overview, Risk Monitoring, Developer Analytics, Timeline), avec préparation des dates',
      'en Power Query, sept mesures DAX, filtrage croisé natif entre transports et objets,',
      'filtre Top N sur la page Timeline, et thème visuel sombre personnalisé. Un site web',
      "dédié (React 19, Vite, HashRouter, hébergé sur GitHub Pages) intègre ce dashboard.",
    ].join(' '),
  },
  {
    id: 'methodology-phase6-alerting',
    topic: 'Phase 6 -- Alerting et automatisation',
    text: [
      "Phase 6 -- Moteur d'alerte (programme Z_PHASE6_ALERTING), la phase la plus",
      "significative de l'audit : le programme initial ne compilait pas, avec deux erreurs",
      'bloquantes (un paramètre de table générique empêchant un SORT, et une lecture d\'un',
      "champ TARSYSTEM inexistant sur la table E070C). Un problème architectural sous-jacent a",
      'aussi été trouvé : le score de risque était recalculé indépendamment des Phases 2/3,',
      "avec un statut qui ne pouvait jamais atteindre FAILED. Corrections : typage correct des",
      'tables, réconciliation pour relire le score/statut déjà calculés dans ZTR_TRANSPORT,',
      'alignement du filtre de sélection, et ajout de la règle "transport bloqué depuis plus',
      'de X jours" (paramètres P_STUCK/P_STUCKD, 14 jours par défaut, déclenchée quand le',
      'statut réel est UNKNOWN et que la date de release dépasse ce seuil). Validation sur 120',
      'jours : 32 transports analysés, 5 signalés (4 à risque HIGH avec des scores 610/170/',
      '170/170, et 1 en échec FAILED malgré un score LOW). Un test d\'envoi email réel a',
      'ensuite révélé un second bug (paramètre PACKING_LIST mal construit, provoquant un',
      'short dump CONVT_NO_NUMBER), corrigé ; l\'email est désormais correctement construit et',
      'mis en file, mais son envoi réel reste bloqué par une authentification SMTP manquante',
      '(smtp.gmail.com:25), une limitation d\'infrastructure côté Basis, hors périmètre du',
      'développement applicatif.',
    ].join(' '),
  },
  {
    id: 'methodology-extension-chatbot',
    topic: 'Extension personnelle -- Assistant IA (RAG)',
    text: [
      "Extension personnelle réalisée au-delà du cahier des charges : un assistant",
      'conversationnel intégré au site web, fondé sur une architecture RAG (Retrieval-',
      'Augmented Generation) combinant OpenAI (embeddings text-embedding-3-small et modèle de',
      'chat gpt-4o-mini) et une base vectorielle Pinecone. Un script d\'ingestion indexe les',
      'données réelles de transport ainsi que le contenu méthodologique du projet. Un serveur',
      'Express expose une route /api/chat, appelée par un widget de discussion flottant',
      "React. Lors de la validation, une anomalie réelle a été détectée (une question",
      'd\'agrégat répondait "4" transports en échec au lieu des 20 réels, car la recherche',
      'vectorielle ne renvoie que les documents les plus proches sémantiquement, jamais',
      "l'intégralité des données) -- corrigée par l'ajout d'un document de résumé global",
      'systématiquement inclus dans le contexte transmis au modèle.',
    ].join(' '),
  },
]
